### ISSUE TITLE
Missing install and configuration description / getting started guide

### ISSUE THREAD

**Issue by munklinde** [plazmdk/homeassistant-wavin#2]
Great work providing this integration !!!

After looking into the code, I managed to get my system setup.

1) Download
2) Unzip
3) Move to custom_components folder in homeassistant configuration folder
4) Modify configuration.yaml
5) Reboot 

Free to use my configuration as example:
wavin:
    tty: /dev/ttyUSB0
    thermostats: [{name: "kitchen", sensor_channel: 0, room_channel: 0},{name: "diningroom", sensor_channel: 1, room_channel: 1},{name: "tvroom", sensor_channel: 2, room_channel: 2},{name: "hall", sensor_channel: 3, room_channel: 3},{name: "bedroom", sensor_channel: 4, room_channel: 4}]

**Comment by plazmdk** [comment]
Thanks for providing these examples - readme has been updated
