### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Strux-DK** [plazmdk/homeassistant-wavin#6]
Hello,
Is it possible to get some more instructions? I'm unsure whether this requires any hardware. Additionally, i tried to follow the steps, but when i come to checking the configuration.yaml file, it says it is invalid:  Integration error: thermostats - Integration 'thermostats' not found. Integration error: wavin - Integration 'wavin' not found.

**Comment by plazmdk** [comment]
This has unfortunately not been updated for years because I switched to this solution instead
https://github.com/paller/Wavin-AHC-9000-mqtt

This project is most likely not compatible with the new versions of HA, and it required a USB RS485 stick connected to the wavin controller

**Comment by munklinde** [comment]
Hello
I still have it running. Though I did not reinstall for a couple of years, but it works fine.
Please ensure to copy the folder named "wavin" to custom_components folder in homeassistant and then restart homeassistant. The integration should then be "known".
