### ISSUE TITLE
Connecting RS485 to the Wavin AHC9000 control unit

### ISSUE THREAD

**Issue by Xayer** [plazmdk/homeassistant-wavin#7]
Hi, I'm wondering how you managed to connect the RS485 pins to the Wavin AHC9000 control unit.

Is it connected to the RJ45 connector?

**Comment by plazmdk** [comment]
Yes, they are using modbus - I believe you can find the pinout here
https://community.openhab.org/t/new-binding-suggestion-wavin-ahc-9000-jablotron-ac-116/28422/105?page=6 
I have myself switched to this setup
https://github.com/paller/Wavin-AHC-9000-mqtt

**Comment by Xayer** [comment]
Thanks a lot! I will look into it.

What's the benefit of moving to the MQTT solution?

**Comment by plazmdk** [comment]
Well, you do not need to have a plugin that has to be updated with home assistant updates - and also the setup uses a ESP powered by the wavin controller and hence less cables.
